pins:
  - pin: 1
    id: E15
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 1
    
  - pin: 2
    id: E14
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 2
    
  - pin: 3
    id: E13
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 3
    
  - pin: 4
    id: E12
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 4
    
  - pin: 5
    id: E11
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 5
    
  - pin: 6
    id: E10
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 6
    
  - pin: 7
    id: E9
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 7
    
  - pin: 8
    id: E8
    class: outputs
    function: High Side Output
    type: ign
    ts_name: Ignition 8

    # Low side

  - pin: 9
    id: D12
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Fuel pump output

  - pin: 10
    id: D11
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Boost controler

  - pin: 11
    id: D10
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Fan output

  - pin: 12
    id: D9
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Tacho out

  - pin: 13
    id: D8
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Low side output 1

  - pin: 14
    id: B12
    class: outputs
    function: Low Side Output
    type: ls
    ts_name: Low side output 2

  - pin: 15
    function: ETB-
    type: etb

  - pin: 16
    function: ETB+
    type: etb

  - pin: 17
    id: D2
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 1
    
  - pin: 18
    id: C12
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 2

  - pin: 19
    id: C8
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 3
    
  - pin: 20
    id: C7
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 4
    
  - pin: 21
    id: C6
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 5
    
  - pin: 22
    id: D15
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 6
    
  - pin: 23
    id: D14
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 7
    
  - pin: 24
    id: D13
    class: outputs
    function: Low Side Output
    type: inj
    ts_name: Injector 8
    
  - pin: 25
    id: EFI_ADC_2
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Clt sensor

  - pin: 26
    id: EFI_ADC_3
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Iat sensor

  - pin: 27
    id: EFI_ADC_5
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: TPS sensor

  - pin: 28
    id: EFI_ADC_4
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Spare analog input 1

  - pin: 29
    id: EFI_ADC_6
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Spare analog input 2

  - pin: 30
    id: EFI_ADC_7
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Spare analog input 3

  - pin: 31
    id: EFI_ADC_15
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Spare analog input 4

  - pin: 32
    function: GND
    type: gnd

  - pin: 33
    id: [B9, B9]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 1

  - pin: 34
    id: EFI_ADC_14
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Spare analog input 5

  - pin: 35
    function: LSU_nermest
    type: lsu

  - pin: 36
    function: LSU_vgnd
    type: lsu

  - pin: 37
    function: LSU_ia
    type: lsu

  - pin: 38
    function: LSU_ip
    type: lsu

  - pin: 39
    function: LSU_heater-
    type: lsu

  - pin: 40
    function: 5V output
    type: 5V

  - pin: 41
    id: [E0, E0]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 2

  - pin: 42
    function: CAN_L
    type: CANL

  - pin: 43
    function: CAN_H
    type: CANH

  - pin: 44
    id: [E6, E6]
    class: [event_inputs, switch_inputs]
    function: Camshaft Sensor (VR+/Hall)
    type: vr hall
    ts_name: Camshaft Sensor

  - pin: 45
    function: Camshaft VR- (do not connect if hall)
    type: vr

  - pin: 46
    id: [E5, E5]
    class: [event_inputs, switch_inputs]
    function: Crankshaft Sensor (VR+/Hall)
    type: hall
    ts_name: Crankshaft Sensor

  - pin: 47
    function: Crankshaft VR- (do not connect if hall)
    type: vr

  - pin: 48
    function: 12V supply from Key (turn on/off power) primary source of +12v
    type: 12V

  - pin: 49
    id: [E4, E4]
    class: [event_inputs, switch_inputs]
    function: Spare trigger input (VR+/Hall)
    type: hall
    ts_name: Spare trigger input

  - pin: 50
    id: EFI_ADC_10
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: MAP sensor

  - pin: 51
    id: EFI_ADC_0
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Battery reference voltage

  - pin: 52
    id: EFI_ADC_1
    class: analog_inputs
    function: Sensor Input
    type: as
    ts_name: Build-in wideband sensor

  - pin: 53
    id: [E2, E2]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 3

  - pin: 54
    id: [E3, E3]
    class: [event_inputs, switch_inputs]
    function: Digital Input
    type: hall
    ts_name: Digital Input 4

info:
  title: KRYPTON
  name: Main Connector
  board_url: 
  directory: KRYPTON
  cid: main
  order: 0
  image:
    file: KRYPTON.png
  pins:
    - pin: 1
      x: 195
      y: 102
    - pin: 2
      x: 225
      y: 102
    - pin: 3
      x: 252
      y: 102
    - pin: 4
      x: 278
      y: 102
    - pin: 5
      x: 308
      y: 102
    - pin: 6
      x: 335
      y: 102
    - pin: 7
      x: 361
      y: 102
    - pin: 8
      x: 390
      y: 102
    - pin: 9
      x: 195
      y: 132
    - pin: 10
      x: 225
      y: 132
    - pin: 11
      x: 252
      y: 132
    - pin: 12
      x: 278
      y: 132
    - pin: 13
      x: 308
      y: 132
    - pin: 14
      x: 335
      y: 132
    - pin: 15
      x: 361
      y: 132
    - pin: 16
      x: 390
      y: 132
    - pin: 17
      x: 195
      y: 163
    - pin: 18
      x: 225
      y: 163
    - pin: 19
      x: 252
      y: 163
    - pin: 20
      x: 278
      y: 163
    - pin: 21
      x: 308
      y: 163
    - pin: 22
      x: 335
      y: 163
    - pin: 23
      x: 361
      y: 163
    - pin: 24
      x: 390
      y: 163
    - pin: 25
      x: 589
      y: 102
    - pin: 26
      x: 618
      y: 102
    - pin: 27
      x: 645
      y: 102
    - pin: 28
      x: 672
      y: 102
    - pin: 29
      x: 702
      y: 102
    - pin: 30
      x: 728
      y: 102
    - pin: 31
      x: 755
      y: 102
    - pin: 32
      x: 784
      y: 102
    - pin: 33
      x: 589
      y: 135
    - pin: 34
      x: 618
      y: 135
    - pin: 35
      x: 645
      y: 135
    - pin: 36
      x: 672
      y: 135
    - pin: 37
      x: 702
      y: 135
    - pin: 38
      x: 728
      y: 135
    - pin: 39
      x: 755
      y: 135
    - pin: 40
      x: 784
      y: 135
    - pin: 41
      x: 589
      y: 163
    - pin: 42
      x: 618
      y: 163
    - pin: 43
      x: 645
      y: 163
    - pin: 44
      x: 672
      y: 163
    - pin: 45
      x: 702
      y: 163
    - pin: 46
      x: 728
      y: 163
    - pin: 47
      x: 755
      y: 163
    - pin: 48
      x: 784
      y: 163



    
 

