name: Generate Interactive Pinouts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Checkout Repository
      - uses: actions/checkout@v4

      # Krok 2: Generate Pinouts
      - name: Generate Pinouts
        uses: chuckwagoncomputing/interactive-pinout@2.15
        with:
          mapping-path: firmware/config/boards/*/connectors/*.yaml
          warnings: "false"
          warning-no-pins: "skip"
          warning-dupe: "error"
          columns: |
            {
            "pin":"Pin Number",
            "ts_name":"TS Name",
            "type":"Type",
            "function":"Typical Function",
            "color":"Pigtail Color"
            }
          print-columns: |
            [
            "function"
            ]
          info-column: "type"
          templates: |
            {
            "___": "pin"
            }
          colors: |
            {
            "12v":"yellow";
            "12V":"yellow";
            "5v":"red",
            "5V":"red",
            "at":"green",
            "av":"brown",
            "can":"blue",
            "din":"lime",
            "etb":"darkcyan",
            "gnd":"darkgreen",
            "gp_high":"aqua",
            "gp_low":"aquamarine",
            "gp_pp":"cyan",
            "hall":"darkolivegreen",
            "high_logic":"gold",
            "hs":"indigo",
            "ign":"magenta",
            "inj":"maroon",
            "ls":"lightgreen",
            "mr":"firebrick",
            "pgnd":"coral",
            "sgnd":"olive",
            "usb":"lightseagreen",
            "vr":"sienna"
            }

      # Krok 3: Spakowanie Plików Pinouts
      - name: Compress Pinouts
        run: tar -czf pinouts.tar.gz pinouts

      # Krok 4: Upload Pinouts jako Artefakt
      - name: Upload Pinouts Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pinouts
          path: pinouts.tar.gz
